# Question 1
What is the result of the following code?
``` python
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
print(c)

```

In [1]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
print(c)

[5 7 9]


The result is [5, 7, 9]

# Question 2

Create a numpy array of 10 zeros. and reshape it to (2, 5)

In [3]:
zero_array = np.zeros(10)
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# reshaping zero_array to (2,5)
zero_array_reshaped = zero_array.reshape(2,5)
print(zero_array_reshaped)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Question 3

Find Mean, Mode, Median, Standard Deviation of the following data


In [6]:
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [7]:
import statistics

In [13]:
data_mean = np.mean(data)
print(f'The mean is {data_mean}')
data_median = np.median(data)
print(f'The median is {data_median}')
data_std = np.std(data)
print(f'The standard deviation is {data_std}')
data_mode = statistics.mode(data)
print(f'The mode is {data_mode}')

The mean is 10.5
The median is 10.5
The standard deviation is 5.766281297335398
The mode is 1


# Question 4
create a 6x6 numpy array with random values and find the min and max values

In [15]:
my6x6 = np.array([[i for i in range(6)] for _ in range(6)])
print(my6x6)

[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]


In [18]:
maximum = np.max(my6x6)
minimum = np.min(my6x6)
print(maximum)
print(minimum)


5
0


# Question 5
Create a 3D numpy array and reshape it to 2D

In [29]:
a_3d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(a_3d_array)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
a_2d_array = a_3d_array.reshape((3,2))

# Question 6
create 1D array from this data

In [23]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [30]:
a_1d_array = np.ravel(data) # method for creating a one Dimensional array
print(a_1d_array)

[1 2 3 4 5 6 7 8 9]


# References

https://bic-berkeley.github.io/psych-214-fall-2016/reshape_and_3d.html